# Connectivity
listen_addresses = '*'
max_connections = 500

# Memory
shared_buffers = 4GB
work_mem = 128MB
maintenance_work_mem = 256MB
checkpoint_completion_target = 0.9

# Checkpoints & WAL
checkpoint_timeout = 15min
checkpoint_completion_target = 0.9
min_wal_size = 1GB
max_wal_size = 4GB

# Performance Tuning for Benchmarking
synchronous_commit = off
full_page_writes = off
random_page_cost = 1.1
effective_cache_size = 6GB

# Logging (Useful for debugging the benchmark)
log_min_duration_statement = 500
