repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0  # Use the latest version found by autoupdate
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        stages: [pre-commit] # Modern stage naming

  - repo: local
    hooks:
      - id: go-fmt
        name: Enforce Formatting
        entry: make fmt
        language: system
        files: '\.go$'
        pass_filenames: false
        stages: [pre-commit]

      - id: go-lint
        name: Enforce Linting
        entry: make lint
        language: system
        files: '\.go$'
        pass_filenames: false
        stages: [pre-commit]
